# #!pip install -U sentence-transformers
# #!pip install chromadb

# import chromadb
# from chromadb.utils import embedding_functions
# from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction
# # from chromadb.utils.text_splitter import CharacterTextSplitter
# # from chromadb.utils.prompt_templates import PROMPT_TEMPLATE_SIMPLE_TEXT
# from chromadb import PersistentClient

# client = chromadb.PersistentClient(path="public/vector")

# sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L12-v2")
# # collection = client.create_collection(name='specs',embedding_function=sentence_transformer_ef,metadata={'hnsw:space':'cosine'})

# # client.delete_collection(name='specs')



# import spacy
# import numpy as np

# nlp = spacy.load("en_core_web_sm")
# topics = ['Physics', 'Chemistry', 'Biology', 'Mathematics', 'Computer Science', 'Medicine', 'Art History', 'Computer Science & Information Technology', 'Law','Statistics']
# txt = "This means that as you zoom into a fractal, you'll see smaller copies of the overall shape, repeating infinitely. Fractals are not limited to simple shapes like squares or circles; they can have intricate and infinitely detailed patterns.One of the most famous fractals is the Mandelbrot set, discovered by mathematician Benoit Mandelbrot in the 1970s. The Mandelbrot set is generated by iterating a simple mathematical formula and determining whether the resulting sequence remains bounded or tends to infinity. Points within the Mandelbrot set are colored black, while points outside the set are colored based on how quickly they diverge to infinity.Fractals have applications in various fields, including mathematics, physics, computer science, and art. In mathematics, fractals provide insights into chaos theory, dynamical systems, and nonlinear dynamics. In physics, fractals are used to model irregular shapes in nature, such as coastlines, clouds, and mountains.Fractal geometry also has practical applications in computer graphics, where it is used to generate realistic-looking terrain, textures, and natural phenomena in video games and visual effects.Additionally, fractals inspire artists and designers with their intricate and mesmerizing patterns, leading to the creation of stunning artworks and architectural designs."
# doc = nlp(txt)

# def nlp_processing():
#     sentences = [sent.text for sent in doc.sents]
#     similarities = []
#     for sentence in sentences:
#         sent_doc = nlp(sentence)
#     for topic in topics:
#       topic_doc = nlp(topic)
#       # print(topic_doc)

#     sent_doc = [token for token in sent_doc]
#     print(sent_doc)

#     type(topic_doc)

# def similarity_topics():
#     collection.add(
#         documents=sentences,
#         ids=[f"id{i}" for i in range(len(documents))],
#         metadatas=[{"genre": g} for g in topics]
#     )

#     results = collection.query(
#         query_texts=["Fractals"],
#         n_results=2,
#         include=['documents','distances','metadatas']
#     )